services:
  # api not working so commenting out for now...
  # iks_reporting_api:
  #   build: .
  #   container_name: iks_reporting_api
  #   image: api
  #   restart: always
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     GRAPHQL_PORT: ${GRAPHQL_PORT}
  #   expose:
  #     - ${GRAPHQL_PORT}
  #   ports:
  #     - ${GRAPHQL_PORT}:4000
  #   command: ["npm", "run", "start"]
  #   depends_on:
  #     ikc_reporting_db:
  #       condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  ikc_reporting_db:
    container_name: ikc_reporting_db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ikc-data:/var/lib/postgresql/data

volumes:
  ikc-data:
    name: ikc-data
  pgadmin-data:
    name: pgadmin-data
